name: CI

on:
  pull_request:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  ios-compat:
    # if the job is triggered by a comment, then it must start with /ci
    if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && startsWith(github.event.comment.body, '/ci'))
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Build and Test 
        run: echo ${{ github.event.pull_request.headRefName }}