name: Release

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  macos-release:
    if: github.event_name == 'workflow_dispatch' || (startsWith(github.ref_name, 'release/') && github.event.issue.pull_request && startsWith(github.event.comment.body, '/release'))
    runs-on: macos-11
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          echo hello
